version: "3.9"

services:
  rstudio:
    build: .
    container_name: rstudio-bioinfo
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=rstudio
    volumes:
      - .:/home/rstudio
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"